samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample.sln, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/FancyMath.h, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/NativeModuleSample.vcxproj, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/ReactPackageProvider.cpp, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/ReactPackageProvider.h, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/ReactPackageProvider.idl, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/packages.config, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/pch.h, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/windows/NativeModuleSample.sln, samples/NativeModuleSample/csharp/windows/NativeModuleSample/ReactPackageProvider.cs, samples/NativeModuleSample/csharp/yarn.lock
* Updated package.json dependencies and re-ran `yarn`:
```json
"peerDependencies": {
"react": "^16.8.6",
"react-native": "^0.60.0-0",
"react-native-windows": "^0.60.0-vnext"
},
"devDependencies": {
"react": "^16.8.6",
"react-native": "^0.60.0-0",
"react-native-windows": "^0.60.0-vnext"
}
```
* Synced CppWinRT version to 2.0.190730.2
* Removed ReactUWP from solutions
* Added Mso and Shared to solutions
* Removed references to Microsoft.ReactNative.Bridge namespace
* Minor code fixes
=> Updating NativeModuleSample to the latest RNW

docs/getting-started.md
Changed from 0.60 to 0.60.0 in the instructions.
=> Typo on the getting started page

website/pages/en/index.js
Fixed a typo in "MacOS desktop and laptop ecosystems". Changed "MacOS dektsop and laptop ecosystems" to "MacOS desktop and laptop ecosystems"
=> Fixed typo in index.js

docs/getting-started.md
This is a minor update to the getting started guide that prefixes the react-native init with npx. This change also removes the global install per the new 0.60 instructions.
This addresses #25 .
=> Update getting-started.md to use npx and removed global react native install

docs/getting-started.md
Forgot to add the npx in front of the init for react-native in the beta installation instructions.
=> npx change to beta instructions

docs/getting-started.md
Not added this prefix to any "react-native" command was causing the command to not be found. This PR fixes that getting started guide issue.
=> npx prefixes added

docs/getting-started.md
Changed the wording for the init project direction call out/prefix as well as added `--dev` to the end of the rnpm CLI instructions.
=> Wording and rnpm `--dev` extension added

docs/getting-started.md
added `--overwrite` at end of second npx command - to ensure metro is overwritten without the user needing to confirm.
This addresses #[4504](https://github.com/microsoft/react-native-windows/issues/4504)
=> added command to overwrite metro without user confirmation

docs/getting-started.md, docs/native-modules.md, docs/rnw-dependencies.md, docs/view-managers.md, website/pages/en/index.js
* Removed mentions of vnext, since 61 drops that release tag
* Reverts windows versions to what 61 supports
=> Remove mentions of 'vnext'

docs/releases.md, website/versioned_docs/version-0.60/releases.md
[PR #4731](https://github.com/microsoft/react-native-windows/pull/4731) in [react-native-windows](https://github.com/microsoft/react-native-windows) repo moved readme.md from the vnext folder to unify them.
=> Update links to new location of readme.md in react-native-windows repo

docs/getting-started.md
The getting started guide had two conventions for the placeholder for the name of a project.
This PR standardizes them on `<projectName>`
=> Update getting-started.md to use `projectName` as a placeholder

docs/parity-status.md
The dates were wrong on the column of implemented modules. Also, it's not terrible helpful, so I removed it.
These modules were also all described as being migrated out, which isn't correct for all of them. Broke into two tables, one for lean core migrations, the other for community modules.
Long term those should be tracked with a [directory](https://github.com/microsoft/react-native-windows/issues/3718), but for now while the list is short this is still helpful.
Fixes #86 86
=> Remove out of date "implemented" column

docs/rnw-dependencies.md
Just following the Getting Started guide may cause the user to have an improper dependency setup leading to the error:
> Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)
Adding a link to guide the user to install the correct version of the platform tools should help avoid confusion.
=> Added instructional link to enable build tools

website/core/Footer.js, website/pages/en/index.js, website/siteConfig.js, website/static/css/docs-prevnext.css, website/static/css/header.css, website/static/css/homepage/HeaderHero.css
This PR updates the home page and introduces the following changes:
* part of getting started text moved outside of the Windows button
* getting started buttons for Windows and macOS
* consistency in the platform naming - [`macOS`](https://www.apple.com/macos/what-is/) instead of `Mac` or `MacOS`
* this includes site name and tagline in the `siteConfig.js`
* "Mac" is the name of certain devices (hardware) made by Apple which are using macOS (AFAIK there is no such general counterpart word for the machines using Windows, PC is the close one, but in principal of definition Macs are Personal Computers too, usually PC term stick best to the Windows powered desktops)
* few small code simplifications
Apple naming may be confusing sometimes and I am not 100% sure if I handled the changes …
=> update home page, add macOS button, macOS instead of Mac

docs/rnm-getting-started.md
An error occurred in Install React Native for macOS.
```
command not found: cd..
```
"cd" command needs space between args. 
```diff
- cd macos && pod install && cd..
+ cd macos && pod install && cd ..
```
=> Fix command error in rnm-getting-started.md

website/versioned_docs/version-0.61/rnm-getting-started.md
An error occurred in Install React Native for macOS.
```
% npx react-native init sample --version 0.61
This will walk you through creating a new React Native project in /Users/shoken/git/sample
Using yarn v1.22.4
Installing 0.61...
yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/0.61: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/shoken/git/sample/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed: yarn add 0.61 --exact
at checkExecSyncError (child_process.js:621:11)
at execSync (child_process.js:657:15)
at run …
```
=> Fix command error in website rnm-getting-started.md

website/versioned_docs/version-0.60/rnw-dependencies.md, website/versioned_docs/version-0.61/rnw-dependencies.md
This PR fix link in The Basics System Requirements in both versions 0.60 and 0.61, when you click in this link appears 404 error.
=> Fix Link the basics system requirements

docs/rnm-getting-started.md
This small PR removes the manual Pods installation step from the latest Getting Started guide for the macOS. 
Refs: microsoft/react-native-macos#366
=> remove manual Pods installation from macOS guide

docs/getting-started.md
Mainly to call out that you can create a C# or C++ app.
=> Options for react-native-windows-init

docs/view-managers.md
We changed the MSRN View Manager command APIs. Update examples to conform to 0.62, which requires some mechanical API changes for C++ View Managers. No changes needed for C# view managers or JS in the example.
=> Update Docs for RNW 0.62 String View Manager Commands

website/pages/en/versions.js
Added the "latest version" of the docs back into this page for quick click/reference. Was accidentally removed in an old merge. Fixes #131 .
=> Versions page master link fix

docs/getting-started.md
DebugPackage and ReleasePackage no longer exist.
=> Updated "Building a standalone [RNW] App" instructions

docs/releases.md
Minor issue/desparity between the releases.md info under the main/next docs folder and the releases.md under the v62 docs.
=> Fix to Releases.md on next docs

docs/native-modules-async.md, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/AsyncMethodExamples.h, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/DataMarshallingExamples.h, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/NativeModuleSample.vcxproj, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/NativeModuleSample.vcxproj.filters, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/ReactPackageProvider.cpp, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/pch.h, samples/NativeModuleSample/csharp/windows/NativeModuleSample/AsyncMethodExamples.cs, samples/NativeModuleSample/csharp/windows/NativeModuleSample/NativeModuleSample.csproj, website/.unbroken_exclusions, website/sidebars.json, website/versioned_docs/version-0.61/native-modules-async.md, website/versioned_docs/version-0.62/native-modules-async.md, website/versioned_sidebars/version-0.61-sidebars.json, website/versioned_sidebars/version-0.62-sidebars.json
This PR adds a new docs page describing how to write a native module with asynchronous methods with asynchronous Windows APIs, as well as a sample `SimpleHttpModule` in C# and C++/WinRT
=> Add native module examples for using async APIs

docs/native-modules-async.md
There were a few typos in the **Using Asynchronous Windows APIs** documentation.
=> Fixed typos

docs/native-modules-setup.md
Close https://github.com/microsoft/react-native-windows/issues/3576.
Close https://github.com/microsoft/react-native-windows/issues/5456.
=> Add info about native module testing and CI

.vscode/settings.json
When searching (especially search & replace!) I find myself frequently excluding the previous versions. 
This change will make it the default in VsCode through a shared settings.json file.
=> Exclude all versioned pages by default from text searches in Visual Studio Code

website/sidebars.json
The PR #213 had the wrong ID for the nuget markdown page so the tab wasn't showing up. I also moved winui into it and moved the experimental tab lower in the list of tabs
=> Fix experimental tab

website/versioned_docs/version-0.62/parity-status.md, website/versioned_docs/version-0.62/supported-community-modules.md, website/versioned_sidebars/version-0.62-sidebars.json
This change updates the docs to include the recently supported modules, and expands the previous table to also discuss macOS support. It also adds a note about reactnative.directory.
Fixes #202 
- Is it worthwhile to have the specific "Supported Version" columns or could this be collapsed to ✔ vs ❌ ?
- Is the macOS version column correct?
- Are we missing any modules?
- This doc currently lives in the Native Modules (Windows) section of the sidebar; is that correct or should it move?
=> Update supported modules table

docs/nuget.md, docs/parity-status.md, docs/supported-community-modules.md, website/versioned_docs/version-0.62/parity-status.md
Few things were missing from the new community modules doc that this PR attempts to fix:
- Supported community modules doc was not added to /docs/ folder and was only present in the versioned 0.62 folder. This will make it not move forward with the website folder since an original id would be missing. This PR adds this file to the docs/ folder
- Same with API parity doc update. That has also been done on docs/ folder
- API parity doc needed a bit more details and cross reference to the new doc.
=> Cross referencing and updating community modules docs

docs/rnm-getting-started.md, website/versioned_docs/version-0.62/rnm-getting-started.md
Making 2 changes based on versioning discussion:
- Updated the Getting started guide for macOS for v0.62 with instructions for new apps as well as upgrading existing apps.
- Updated the "next" version to indicate v0.63 is not supported in React Native for macOS yet and point to the 0.62 version as latest. The link in this file will be broken until website version is upgraded.
=> Updating macOS getting started guide

.github/workflows/samples-CameraDemo-ci-upgrade.yml, .github/workflows/samples-CameraDemo-ci.yml, samples/CameraDemo/App.js, samples/CameraDemo/package.json, samples/CameraDemo/yarn.lock
* Updated react-native-camera to 3.38.0, which supports ARM64 on windows
* Removed record maxDuration
* Updated CI
=> Enable ARM64 for CameraDemo

website/versioned_docs/version-0.63/rnm-getting-started.md, website/versioned_sidebars/version-0.63-sidebars.json
One more fix following #237 to make sure the 63 versioned docs are pointing to the right links.
=> Fixing links for 63 versioned docs

docs/native-modules-setup.md, docs/native-modules.md, website/versioned_docs/version-0.63/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules.md
Update native docs with corrected information and add troubleshooting and info about methods returning complex types like string.
Fixes: https://github.com/microsoft/react-native-windows/issues/5910
=> Native modules doc updates

docs/native-modules.md, website/versioned_docs/version-0.62/native-modules.md, website/versioned_docs/version-0.63/native-modules.md
Add C#-C++ interop instructions since we've had a number of people get confused/blocked by the indecipherable .net error
`0x80131040 : The located assembly's manifest definition does not match the assembly reference.`
Fixes https://github.com/microsoft/react-native-windows/issues/5858
=> Add C# - C++ interop instructions

docs/rnm-dependencies.md, samples/rssreader/macos/Podfile, samples/rssreader/macos/rssreader.xcodeproj/project.pbxproj, website/pages/en/index.js, website/versioned_docs/version-0.61/rnm-dependencies.md
Currently website mentions 10.12 SDK on the front page and 10.14 in system requirement, when 10.14 was the right version. After the merge of linked PR in the `react-native-macos` repository the correct version will be 10.13.
This PR updates the minimum macOS SDK version across the whole repository. It affects home page, getting started guide, and RRS Reader sample files.
Unfortunately [Apple release notes](https://developer.apple.com/documentation/macos-release-notes) are available from 10.14 onwards, at the beginning I want to use the last [10.13 update page](https://support.apple.com/en-us/HT208864) (like on some instances before, but I was able to find the [High Sierra release post](https://www.apple.com/newsroom/2017/09/macos-high-sierra-now-available-as-a-free-update/) in the Apple …
=> unify the minimum macOS SDK version

docs/win10-compat.md, website/versioned_docs/version-0.63/win10-compat.md
Adds 63 to the windows compat table (same as 62, but causing some confusion).
Closes #259
=> Add 63 to win10-compat

samples/Calculator/yarn.lock, samples/CameraDemo/yarn.lock, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/yarn.lock
* Updated yarn.lock in samples with latest versions
* NativeModuleSample/csharp now builds
=> Update samples with 0.63.2

docs/native-modules.md
Correct the example to callback to `something.Completed([result] (const auto& operation, const auto& status)`
=> Fix parameters order in the async sample.

docs/metro-config-out-tree-platforms.md, website/sidebars.json
A common issue people hit is around their metro config.  This adds a starting set of steps for people to investigate their issue.
=> Add metro troubleshooting document

docs/getting-started.md
Adds a warning to try disabling UseWebDebugger when building for Release and there are differences in behavior between Release and Debug builds.
This change in documentation is motivated by having run into a situation where the react-native-windows application ran in the Debug configuration but just showed a blank screen in the Release configuration. In this case it was caused by the use of JavaScript's method `Object.fromEntries`, which is implemented in V8 but not supported in the Chakra release. Disabling `UseWebDebugger` in Debug allowed me to see the exception that `Object` doesn't have `fromEntries` bubble up into the popup.
I'd expect this issue to become more common as developers and modules start using more recent ECMAScript features that are not supported by Chakra.
Here's an …
=> Add Web Debugger warning to Release build docs

.spelling, docs/hermes.md
The previous instructions didn't work outside of the react-native-windows repo, so new logic was added in 0.64 to allow properly opting into Hermes. These docs explain how to use it.
Validated everything looks correct when viewing the live preview of the docs site.
=> Add docs for Hermes Consumption in RNW 0.64

website/versioned_docs/version-0.63/rnw-dependencies.md
Fixes #318 . backport the section's text from vNext
=> Fix rn deps link in 0.63

docs/rnw-dependencies.md
https://github.com/microsoft/react-native-windows/pull/6548 means we will start requiring VS 16.5 or later. Add that as information to the docs.
=> Mention VS 16.5 Requirements

docs/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md
Updated versions for Nuget and Msbuild in .yml code snippet. These were the versions I needed to update to for CI Loop to work on RN Gallery. Old versions apparently use deprecated calls.
=> Update Versions in CI Loop Sample Code

docs/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md
Remove Nuget setup from CI Loop Example Code for 64+ because of RNW #6548. Now using built in nuget within msbuild.
=> Remove Nuget Setup from CI Loop Example Code

docs/nuget.md
wrong casing on a doc. Note that this doc is not currently discoverable, it's not in the sidebar or anything, but building the website generates a warning due to a broken link (it's not really broken on Windows, but worth fixing anyway)
=> fix link casing

docs/rnw-dependencies.md
Fixes #339
This changes the recommendation from a specific version of Node 12 to instead install latest LTS, which is the behavior of the dependency script. We should update if we see incompatibilities, but should be making sure latest LTS works as expected anyways.
=> Recommend Installing Node LTS

docs/hermes.md
We don't really have channels or anything yet. Keeping hard version numbers until Hermes NuGet package is downloaded by default and we don't need to worry about this.
=> Update Hermes NuGet Package Version

docs/native-modules-setup.md
The community module setup guide in versioned docs references specific version numbers, but instead calls for canary in the unversioned docs. Replace it with something generic that could be used across new versions if we don't update it.
=> Evergreen version numbers for NM Setup Guide

docs/view-managers.md, website/versioned_docs/version-0.63/view-managers.md
The subsection headers were a size small, making it hard to read(compared to the size up as in "Native Modules" page). 
Also, some code snippets were missing syntax highlighting, for example:
=> Improved Readability for View Managers Documentation

website/versioned_docs/version-0.63/rnw-dependencies.md
Nodejs version update for system requirements and a few others, as requested backported to 0.63
https://github.com/microsoft/react-native-windows/issues/7145
=> Backport System Requirement Page Fix to 0.63, closes RNW #7145

docs/getting-started.md, website/versioned_docs/version-0.63/getting-started.md
Following the Get Started guide omits a now required step to run the auto-link command which wasn't previously called out as part of the "Using Visual Studio" steps. This PR adds that detail.
=> Update VS instructions with autolink step

docs/hermes.md
Depends on https://github.com/microsoft/react-native-windows/pull/7101/files
This updates Hermes instructions for new build logic, changes headings between macOS and Windows to be consistent, and moves the macOS section below Windows, since Windows has more usage.
=> Update Hermes Instructions

docs/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md
Two of the links in the "Choose Your Adventure" section on the [Native Modules Setup](https://microsoft.github.io/react-native-windows/docs/next/native-modules-setup) page were broken. I fixed the links in master and 0.63
=> Fixing Broken Links in Documentation 

docs/rnw-dependencies.md
In the list of manual installation steps, we don't mention a VS component that needs to be installed in order to build the project.
=> Fix missing VS dep info

docs/native-modules-setup.md, website/versioned_docs/version-0.60/native-modules-setup.md, website/versioned_docs/version-0.61/native-modules-setup.md, website/versioned_docs/version-0.62/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md
* Add warning to top that this doc is version specific
* Update text to clarify that the CLI new lib project is 0.64+
Addresses: https://github.com/microsoft/react-native-windows/issues/6829
=> Update native module setup docs with version info

.github/scripts/CheckUnbrokenExclusions.ps1, .github/workflows/website-pr.yml, website/.unbroken_exclusions, website/fix-unbroken.js
Docusarus rewrites the relative URLs for markdown files, but not for assets. This causes unbroken to freak out. So we have the fix-unbroken.js script to generate an exclusions file so unbroken only catches "real" unbroken links.
The script should be run any time someone changes links, add/removed markdown files or assets, etc, however people constantly forget, and their PR fails. Or users add exclusions manually to the file, and then the script overwrites them the next time it's run.
This PR updates fix-unbroken.js to read in the list of statically define exclusions from the existing file and keep them in the newly generated file. It also adds a check to the Website PR to make sure that the file is up to date, and more specifically, give a useful error message so people re-run the script.
=> Update fix-unbroken.js to load existing file, add PR to check file is up to date

docs/getting-started.md
The referenced issue is no longer re levant, but we still use a windows specific blocklist. Remove the stale issue, and fix some typos.
=> Update description of "--overwrite" flag

website/sidebars.json
Adds back the NuGet page - Docusaurus is case sensitive wrt page IDs and we recently changed the casing of the ID to make spell checking happy
=> Restore NuGet page

docs/native-modules-async.md
This pull request fixes #427 
It describes the usage of `UIDispatcher.Post()` method in the basic scenarios for both C# and C++.
---
The description contains the brief introduction explaining why is it necessary to use the `UIDispatcher` and points to the decs about `IReactDispatcher` and *FileOpenPicker* used in these examples (to avoid confusions and to present the control that's related to the UI thread).
There are both C# and C++ examples, both having the same descriptions and steps in them.
Note that the code for launching and handling the *FileOpenPicker* is as basic as it can be. It is not the part of this guide to explain the file handling in details. For more curious readers I've linked the official docs about it.
=> Describe `UIDispatcher`'s usage in the Using Asynchronous Windows APIs document

docs/native-modules-setup.md
This pull request removes the `--module-name` option from the example of creating the native module library project using the [create-react-native-module](https://github.com/brodybits/create-react-native-module) library.
The `--module-name` option has been renamed to `--package-name` in [PR#431](https://github.com/brodybits/create-react-native-module/pull/431), moreover it is optional to use, as it defaults to the name given in the parameter.
---
Another change introduced in this pull request is the separation of following official React Native instructions from following the *bat* code steps presented below it.
React Native instructions use [callstack/react-native-builder-bob](https://github.com/callstack/react-native-builder-bob) while examples presented in these docs use …
=> Fix: `--module-name` is no longer supported in `create-react-native-module`

docs/getting-started.md
=> add `npm start` option to getting-started.md

.github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-Calculator-ci-upgrade.yml, .github/workflows/samples-CalculatorNuGet-ci.yml, .github/workflows/samples-CameraDemo-ci-upgrade.yml, .github/workflows/samples-CameraDemo-ci.yml, .github/workflows/samples-NativeModuleSample-CI.yml, .github/workflows/samples-NativeModuleSample-ci-upgrade.yml
We no longer build ARM in 0.65, so the upgrade CI fails prematurely. This PR removes that config from our workflows so we can get a better idea of what other issues there may be upgrading to 0.65.
=> Remove ARM from sample CI in preparation for 65 upgrade

.github/workflows/samples-RssReader-CI.yml, .github/workflows/samples-RssReader-ci-upgrade.yml, samples/rssreader/yarn.lock
* Bumped react-native-windows from 0.62.0 to 0.62.22 to fix build break.
* Removed ARM from CI workflows
=> Fix rssreader sample build

docs/native-modules-jsvalue.md, docs/native-modules.md, docs/nuget.md, docs/view-managers.md
This adds code tabs to our usage docs, so that we get this kind of header where people can pick which language to see docs for:
=> Add code tabs, consolidate some content

docs/rnw-dependencies.md, website/siteConfig.js, website/static/css/code-block-buttons.css, website/static/js/code-block-buttons.js, website/versioned_docs/version-0.64/rnw-dependencies.md
This gets rid of the one off hacky copy button in rnw-dependencies and uses the recommended way to add the copy button to code blocks - see https://gist.github.com/yangshun/55db997ed0f8f4e6527571fc3bee4675
Also created an aka.ms redirect for the dependencies ps1 so it looks neater on the website, it's easier to remember, and allows us to move the file if we ever need to : )
=> Add copy button to all code blocks as recently documented by docusaurus

.github/workflows/website-pr.yml, docs/windowsbrush-and-theme.md
This repo uses markdown-spellcheck to catch document spelling errors. Its output shows the word it does not recognize via coloration. It uses Chalk to do this, which will by default noop when running in a non-interactive console (i.e. something that doesn't know how to show color).
This lack of color means we can't tell the word being complained about. GitHub Actions can render color, but we need to force chalk to. We pass the `--color` CLI arg for chalk to read, and override default logic to omit ANSI escape codes.
=> Fix Highlighting of Misspelled Words in CI Output 

docs/iviewwindowsprops-api-windows.md
=> Remove reference to acceptsKeyboardFocus

docs/apptheme-api-windows.md
Everything in AppTheme that overlapped with Appearance was removed. Remove the APIs, and rewrite the sample to not use them. We convert from a class component to function component when updating the sample. The methods are also exposing as property getters instead of methods, so we change the examples there.
=> Update AppTheme Docs for 0.65

website/siteConfig.js
**_Why_**
Flip default version displayed by website to 0.65.
=> Flip Default Version to 0.65

docs/win10-compat.md
Hermes is going to load ICU dlls from Windows with this PR : https://github.com/microsoft/react-native-windows/pull/8657
This wiki has some details on the ICU consumption in Windows: https://www.osgwiki.com/wiki/Using_ICU_on_Windows
ICU is available in Windows from RS2+ (Version 1703). One of the requirements is that the client must call CoInitializeEx prior to first call to ICU. 
19H1+ (Version 1903) doesn't require CoInitializeEx call, and the integration is cleaner. Hence, we want to keep 19H1+ as the minimum supported version for full support of locale aware APIs.
=> Updating the compatibility matrix to include the hermes+ICU limitations.

docs/getting-started.md
Unfortunately the `--getting-started` option is no longer used (for the v7).
This is stated in the npm docs -> [Compatibility with Older npm Versions](https://docs.npmjs.com/cli/v7/commands/npx#compatibility-with-older-npx-versions).
So this pull request removes the information about using this option as a workaround for issues with global installation.
**How to test:**
Information about this option is deprecated is also printed when used:
```
PS C:\Dev\ReproProjects> npx --ignore-existing react-native init RNWReproApp
npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
```
---
I didn't find any information what about other solutions to conflicts with globally installed packages, but on the other hand as it's stated in the explanation:
> Locally …
=> Remove `--ignore-existing` option from Getting Started page

.github/workflows/samples-Calculator-pr.yml, .github/workflows/samples-CalculatorNuGet-ci-upgrade.yml, .github/workflows/samples-CalculatorNuGet-pr.yml, .github/workflows/samples-CameraDemo-pr.yml, .github/workflows/samples-NativeModuleSample-pr.yml, .github/workflows/samples-RssReader-pr.yml
There's no need to run the PR workflow because it won't catch any problems in the CI files.
=> Stop running PR pipeline when updating CI files

website/sidebars.json
**_Why_**
In #558, PR is missing update to sidebars. Page will currently not be shown on webstie.
=> Add Setup CI Page to Sidebars

docs/setup-ci.md
Makes the example code match each other. Before was using both GitHubActionsWorkflow.pfx and EncodedKey.pfx but resolves it to use just GitHubActionsWorkflow.pfx.
Makes the documentation easier to understand.
=> Makes Filepath names the same in examples

.github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-Calculator-ci-upgrade.yml
Recent changes broke the CI for Calculator Workflow because the default pathing was left in from docs. This fixes the pathing to the correct sample path 
Hopefully fixes the CI broke in https://github.com/microsoft/react-native-windows-samples/pull/591
=> Adds Correct Pathing to Calculator Workflow

.github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-Calculator-ci-upgrade.yml
Fixes the path to the certificate in react-native run-windows to use a direct path. 
Hopefully fixes the broken CI from https://github.com/microsoft/react-native-windows-samples/pull/592 and https://github.com/microsoft/react-native-windows-samples/pull/591
=> Adds Direct Path to Certificates in Calculator workflow

.github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-Calculator-ci-upgrade.yml
Removes pathing in general for certificate to just use the working directory.
Fix Calculator CI
=> Removes pfx Pathing to use working directory

.github/workflows/samples-Calculator-ci-upgrade.yml, samples/Calculator/windows/Calculator/Calculator.vcxproj
This should fix the Calculator Workflow, tested locally and works. AppxPackageSigningEnabled needed to be removed and pathing fixed for Calculator Upgrade Workflow :)
To Fix Calculator Workflow broken by removing certificates
=> Removes Calculator AppxPackageSigningEnabled and Updates Workflow

.github/workflows/samples-RssReader-CI.yml, .github/workflows/samples-RssReader-ci-upgrade.yml, samples/rssreader/windows/rssreader/rssreader.vcxproj
Removes certificate for RSSReader sample app. Thus the corresponding workflow has to be changed to use the new secret certificate.
#527. Supports movement to remove temporary certificates from RNW repos. The current CI for rssreader also fails since the current temporary certificate is expired.
=> Removes Certificate and Updates Workflow for RSSReader

docs/flyout-component-windows.md, docs/popup-component-windows.md
Add link to React Native Gallery App (http://aka.ms/reactnativegalleryapp) and corresponding example pages (https://github.com/microsoft/react-native-gallery/blob/main/src/examples/FlyoutExamplePage.tsx \ https://github.com/microsoft/react-native-gallery/blob/main/src/examples/PopupExamplePage.tsx) to Popup/Flyout Documentation
When looking at just the documentation, it's hard to find examples of popup/flyout. This leads the user to Gallery App which has examples of both.
Resolves #29
Added to bottom of popup/flyout page
=> Adds link to RN Gallery Examples for Popup and Flyout

docs/native-modules-autolinking.md
There's a new --no-telemetry flag for npx react-native autolink-windows that needs to be captured in the docs.
Resolves #602
=> Add --no-telemetry Option to Autolinking Documentation

website/versioned_docs/version-0.64/rnm-getting-started.md
We had this error in our 0.63 docs but at some point it got omitted in our 0.64 docs. This change adds it back.
Someone in the OSS community reached out having hit this error. We should at least cover it in our documentation for now until a proper fix to the CLI tools is made.
Resolves [ProjectName not found error]
I validated it shows up as expected on my localhost.
=> (macOS) Project name error to 0.64

docs/parity-status.md, website/core/Footer.js, website/pages/en/index.js
I think the term "API Parity" is not super intuitive for people outside the team/Microsoft. Renaming the tab to include "Components and APIs" might make more sense given the content of that page and since we rely on the RN Core documentation linked there for our non-windows-specific API documentation.
=> API Parity Page Rename

.github/workflows/samples-Calculator-ci-upgrade.yml
Fixes Calculator CI (Upgrade)/Csharp added in #606 by adding `--language` option to `react-native-windows-init`. Previously, it was installing the CppWinrt version. 
Workflow is currently broken for Calculator CI (Upgrade)/Csharp
=> Fixes Calculator CI (Upgrade)/Csharp by adding --language

docs/winui3.md, website/versioned_docs/version-0.62/winui3.md, website/versioned_docs/version-0.63/winui3.md, website/versioned_docs/version-0.64/winui3.md, website/versioned_docs/version-0.67/winui3.md
There's no need to specify the version as the react-native-windows-init
command will automatically find the right version for the existing
project.
Also, this means one less place we need to bump the version when
snapping docs for a new release.
=> Remove version specification from winui pages

docs/native-modules-using.md, website/.unbroken_exclusions, website/versioned_docs/version-0.63/native-modules-using.md, website/versioned_docs/version-0.64/native-modules-using.md
This PR updates the "Using Community Native Modules" doc to mention
the role of autolinking and link to its page.
Closes #342
=> Add mention of autolinking to Using Community Native Modules doc

website/pages/en/init-cli.js
Making a separate static page to document react-native-windows-init CLI.
See #607 for page getting linked up to existing pages.
=> Add Static Page for react-native-windows-init CLI Page

website/fix-unbroken.js
The fix-unbroken script was accidentally rewriting `https://` as `https:/` which broke filtering of URLs in blog posts (like `account.microsoft.com` in #639).
=> Fix fix-unbroken to not sanitize external urls

docs/native-modules.md, website/versioned_docs/version-0.62/native-modules.md, website/versioned_docs/version-0.63/native-modules.md, website/versioned_docs/version-0.64/native-modules.md, website/versioned_docs/version-0.65/native-modules.md
Could be more documentation based on the content of [NativeModules.h](https://github.com/microsoft/react-native-windows/blob/0dfe9decb4390c4b77e0837e69c4a25878034960/vnext/Microsoft.ReactNative.Cxx/NativeModules.h), but followed the pattern of others to just put a quick sentence. 
Added on all versions back to 0.62, which is when these were added.
=> Adding ReactInit and ReactFunction

website/versioned_docs/version-0.60/native-modules-advanced.md, website/versioned_docs/version-0.60/native-modules-setup.md, website/versioned_docs/version-0.60/native-modules.md, website/versioned_docs/version-0.60/releases.md, website/versioned_docs/version-0.60/view-managers.md, website/versioned_docs/version-0.61/native-modules-setup.md, website/versioned_docs/version-0.61/native-modules.md, website/versioned_docs/version-0.61/view-managers.md, website/versioned_docs/version-0.62/native-modules-advanced.md, website/versioned_docs/version-0.62/native-modules-setup.md, website/versioned_docs/version-0.62/native-modules.md, website/versioned_docs/version-0.62/rnw-dependencies.md, website/versioned_docs/version-0.62/view-managers.md, website/versioned_docs/version-0.63/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules.md, website/versioned_docs/version-0.63/rnw-dependencies.md, website/versioned_docs/version-0.63/view-managers.md, website/versioned_docs/version-0.64/getting-started.md, website/versioned_docs/version-0.64/native-modules-advanced.md, website/versioned_docs/version-0.64/native-modules-setup.md, website/versioned_docs/version-0.64/native-modules.md, website/versioned_docs/version-0.64/view-managers.md
We renamed the RNW default branch from master to main, but there are still some old links.
=> Update links from RNW master to RNW main

.github/workflows/add-issues-to-bug-board.yml
Using a new [GitHub action (beta) ](https://github.com/marketplace/actions/add-to-github-projects-beta)to automatically add new issues into RN Bug Board for easier triage.
=> workflow for adding issues to bug board, using rnbot token

docs/managing-cpp-deps.md, website/.unbroken_exclusions, website/versioned_docs/version-0.64/nuget-update.md, website/versioned_docs/version-0.64/nuget.md, website/versioned_docs/version-0.65/nuget.md, website/versioned_docs/version-0.66/nuget.md, website/versioned_docs/version-0.68/managing-cpp-deps.md, website/versioned_docs/version-0.68/nuget.md
Changes were made starting with RNW 0.68 to make switching between
building from RNW source and nugets easier.
This PR updates the docs to reflect these easier steps for RNW >= 0.68
and also to clarify the correct steps for earlier versions.
Addressing the confusion from the older steps asking for unnecessary
changes. See https://github.com/microsoft/react-native-windows/issues/9937
=> Update Experimental NuGet documentation

website/pages/en/init-cli.js, website/pages/en/resources-news-social.js, website/pages/en/resources-showcase.js, website/pages/en/resources-videos.js, website/pages/en/resources.js, website/pages/en/versions.js
This PR adds titles to each of the static js pages (rather than
defaulting the not useful full main site title.
This PR also cleans up the ini-cli page to better align with the styles
of the other static pages.
=> Update static js pages with titles and proper site styles

website/pages/en/support.js
Updating the support dates for 0.68 and 0.69 now that 0.69 has been released.
With each new release, we need to set the proper support dates for the prior version.
=> Update support page with new dates because of 0.69 release

docs/native-modules-advanced.md, website/versioned_docs/version-0.60/native-modules-advanced.md, website/versioned_docs/version-0.62/native-modules-advanced.md, website/versioned_docs/version-0.64/native-modules-advanced.md, website/versioned_docs/version-0.65/native-modules-advanced.md
The sample C# code given in the Native Modules (Advanced) page is incorrect. First, there is no `IReactModuleBuilder.SetName` method (it might be left over from an earlier iteration of the API).
Also, when passing an `IJSValueWriter` to a `MethodResultCallback`, the writer must contain an array of arguments to pass to the callback. Even if the callback has only one argument, it must be wrapped in an array for the (de)serialization to work.
Closes https://github.com/microsoft/react-native-windows/issues/10591
=> Fix module builder bugs in "Native Modules (Advanced)" page

website/pages/en/support.js
Remove RNW versions from the support matrix which are no longer supported.
Versions that are no longer supported do not need to take up space, otherwise the support policy doc will grow indefinitely.
=> Remove Unsupported versions from support matrix

docs/rnw-dependencies.md, website/versioned_docs/version-0.62/rnw-dependencies.md, website/versioned_docs/version-0.63/rnw-dependencies.md, website/versioned_docs/version-0.64/rnw-dependencies.md, website/versioned_docs/version-0.65/rnw-dependencies.md, website/versioned_docs/version-0.66/rnw-dependencies.md
RNW 0.71 and later will require VS 2022, so the dependency script has changed.
Related https://github.com/microsoft/react-native-windows/pull/9916
We shouldn't tell people to download the latest script if they're still trying to target RNW <= 0.70.
Closes #736 
N/A
=> Update RNW dependency on VS 2022

docs/debugging-javascript.md, website/sidebars.json, website/versioned_docs/version-0.71/debugging-javascript.md, website/versioned_sidebars/version-0.71-sidebars.json
This PR adds a new doc outlining how to debug the JavaScript of your RNW application, including support matrices and step-by-step instructions for connecting all supported JS debuggers.
This doc was made by testing **every** combination against RNW 0.71 with newly created RNW projects. These steps *may* work for older RNW versions, but I haven't tested that (yet), so I won't backport the doc to earlier versions until I'm sure.
=> New JavaScript Debugging Doc

docs/rnm-getting-started.md
The doc was stale and pointing visitors to the old stable page
=> Updated stale reference from 0.64 to 0.68

website/versioned_docs/version-0.67/debugging-javascript.md, website/versioned_sidebars/version-0.67-sidebars.json, website/versioned_sidebars/version-0.68-sidebars.json, website/versioned_sidebars/version-0.70-sidebars.json
I've confirmed that the instructions for JavaScript Debugging that I wrote for RNW 0.71 actually all work as-is for RNW 0.67.
So this PR backports that doc so it's available in RNW >= 0.67.
=> Backport JavaScript Debugging Docs to 0.67

docs/debugging-javascript.md, website/versioned_docs/version-0.67/debugging-javascript.md
This PR adds the necessary steps to the JavaScript Debugging doc to set up Direct Debugging with the Edge Developer Tools.
=> Add the Edge Developer Tools for Direct Debugging

website/pages/en/support.js
0.70 moved into Maintenance Support on 2/28/2023.
=> Update Support matrix, 0.70 now in Maintenance

docs/native-modules-advanced.md, docs/native-modules-vs-turbo-modules.md, docs/native-modules.md, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/ReactPackageProvider.cpp
TurboModule docs do not mention or show the need to use getConstants() to access constants.  And a couple of other minor fixes
Fixes at least some of the issues from #797
=> Update some of the TurboModule documentation

docs/getting-started.md
If you paste the example into zsh without quoting the version you get:
```
npx react-native init foobar --template react-native@^0.71.0
zsh: no matches found: react-native@^0.71.0
```
You support more shells from the docs.
=> Support zsh when creating a react-native application

docs/getting-started.md, website/versioned_docs/version-0.71/getting-started.md
Remove reference to `react-native-template-typescript` template which has been deprecated since React Native added first-class support for Typescript in version 0.71
=> Outdated typescript instructions

.github/workflows/ci.yml, .github/workflows/pr.yml
This PR adds AppServiceDemo to the list of samples built by CI/PR workflows.
All active samples should have PR/CI to verify they still build. AppServiceDemo is still targeting RNW 0.67 (which is out of support) but it still builds. If/until we decide to deprecate AppServiceDemo, I'd rather we know whether or not it still builds.
N/A
=> Add CI for AppServiceDemo

website/versioned_docs/version-0.64/rnm-getting-started.md, website/versioned_docs/version-0.66/rnm-getting-started.md, website/versioned_docs/version-0.68/rnm-getting-started.md, website/versioned_docs/version-0.71/rnm-getting-started.md
PR #828 was merged without fixing spelling mistakes, which causes CI to fail. This PR fixes the spelling mistakes and also puts the correct versioned pages into place so they appear on the website.
=> Fix macOS getting started page

website/pages/en/support.js
0.72 preview is out so we should have that row in the support table.
Also, it's probably a good idea to keep older **Unsupported** versions in the table for a little while, at least so customers can see *when* that version went out of support.
With 0.70 moving out of Maintenance, we end up with only 1 supported release: 0.71. But it doesn't capture the history if we constantly remove the unsupported versions from the matrix entirely.
N/A
=> Update support.js with 0.72 preview, older versions

.github/ISSUE_TEMPLATE/bug-report-documentation.yaml, .github/ISSUE_TEMPLATE/bug-report-sample.yaml, .github/ISSUE_TEMPLATE/request-documentation.yaml, .github/ISSUE_TEMPLATE/request-sample.yaml
- Updates the version command in the issue template
- Adds more current SDK versions
- Update VS versions
- Removes the default title from the template (which forces people to fill it in)
Command in the form was wrong. Requires same fix as [this](https://github.com/microsoft/react-native-windows/commit/dfef19308f953f9971d08457bfc645ce2cc6f587).
=> Fix version command in issue template

docs/rnm-getting-started.md
Hello,
Goal of this PR is to use latest version of CLI when initializing the project same as in React Native docs. Also without the `"` I was getting an error in my console: `zsh: no matches found: react-native@^0.71.0`
=> docs: use latest react-native cli

docs/winui3.md, website/versioned_docs/version-0.62/winui3.md, website/versioned_docs/version-0.63/winui3.md, website/versioned_docs/version-0.64/winui3.md, website/versioned_docs/version-0.67/winui3.md
As per this [PR](https://github.com/microsoft/microsoft-ui-xaml/pull/8570), the location of the WinUI3 docs have moved.
=> Fix deprecated WinUI3 link

docs/getting-started.md, website/.unbroken_exclusions, website/versioned_docs/version-0.72/getting-started.md
The template for react-native@0.72.0 is broken if you're using the recommended Node 16. RNW now requires a minimum of RN 0.72.3 to operate.
This PR fixes the documentation by specifying the NPM tags rather than static version numbers in our steps for creating a new project. IT also adds some comments to make sure the correct tag is used in the future.
Related: https://github.com/microsoft/react-native-windows/pull/11878
Related: https://github.com/microsoft/react-native-windows/issues/11909
=> Fix version of RN init in Getting Started

docs/win10-compat.md, website/versioned_docs/version-0.60/win10-compat.md
Update the win 10 compat page with the correct min windows versions for RNW versions.
We've changed the minimum version of Windows SDK targeted by RNW in 0.72, this table needs to be updated.
N/A
=> Fix win10compat page for RNW 72 reqs

website/pages/en/support.js
RNW 0.71 entered maintenance support on 7/31/23.
=> Move 0.71 into maintenance as per schedule

docs/debugging-javascript.md, website/versioned_docs/version-0.67/debugging-javascript.md
Fixes the instructions for VS Code debugging scenarios.
The current instructions don't always work with the latest versions of VS Code (with or without the React Native Tools extension). VS Code provides multiple different UI flows for getting the same result which can be confusing.
Resolves #876 
N/A
=> Fix the instuctions for VS Code debugging

docs/getting-started.md, docs/nuget.md, website/.unbroken_exclusions, website/versioned_docs/version-0.63/nuget.md, website/versioned_docs/version-0.71/getting-started.md, website/versioned_docs/version-0.71/rnm-getting-started.md, website/versioned_docs/version-0.72/getting-started.md
Docs specify using `npx react-native@latest init` instead of just `npx react-native init`.
Some developer machines may have cruft on their machines that will cause the wrong version to be used, this is also why the command warns you to to specify the version when it's mising.
Resolves https://github.com/microsoft/react-native-windows/issues/12191
N/A
=> Update to specify react-native version when creating a new project

.spelling, docs/debugging-javascript.md, website/versioned_docs/version-0.67/debugging-javascript.md
This PR adds the steps to direct debug Hermes using Visual Studio. Discovered while investigating https://github.com/microsoft/react-native-windows/issues/12113.
Also some minor formatting cleanup.
To help developers who would prefer to use Visual Studio to direct debug JavaScript.
N/A
=> Add steps to direct debug Hermes with Visual Studio

docs/rnm-getting-started.md
Changes `init` command to use `--version` rather than `--template`.
Simplicity.
=> chore: use `--version` instead of `--template`

docs/rnw-dependencies.md
Other frameworks like Electron or partially Tauri allow developing and building for Windows, so it might not be obvious for newcomers that this requirement exist. I wasn't able to find it in any doc or top google results.
=> "System Requirements" doc: state explicitly that you have to be on Windows for development and building

docs/getting-started.md, website/versioned_docs/version-0.72/getting-started.md, website/versioned_docs/version-0.73/getting-started.md
Installation instructions, when ran as they are now, currently produce the following error for me:
```
No compatible version of react-native-windows found.
The latest supported version is react-native-windows@0.73.3.
Please modify your application to use react-native@^0.73 or another supported version of react-native and try again.
NoAutoMatchingReactNativeWindows:
No compatible version of react-native-windows found.
The latest supported version is react-native-windows@0.73.3.
Please modify your application to use react-native@^0.73 or another supported version of react-native and try again.
```
Just running the react-native "init" without pointing to a nightly version works for me. I've also reproduced the error and the solution on another system (with another OS).
=> Remove "nightly" from installation instructions

website/versioned_docs/version-0.72/getting-started.md
Some transitive dependencies require Node 18 even if we only require Node 16. Added the workaround to unlock new projects with RNW 0.72 and Node 16. See https://github.com/microsoft/react-native-windows/issues/12711
To help with new devs crating new RNW 0.72 apps.
N/A
=> [0.72] Add workaround to keep using Node 16

.spelling, docs/textinput-component-windows.md, website/sidebars.json
Adds TextInput into components so we can document windows-specific properties.
There is currently no documentation for these properties even though they get used quite often. This adds a section to the components so it's easily discoverable. But let me know if there's a better place for these properties!
Resolves #916
=> Add TextInput windows-specific properties to documentation

docs/debugging-javascript.md, docs/getting-started.md, docs/hermes.md, website/versioned_docs/version-0.67/debugging-javascript.md, website/versioned_docs/version-0.73/debugging-javascript.md, website/versioned_docs/version-0.73/getting-started.md, website/versioned_docs/version-0.73/hermes.md
This PR updates our javascript debugging docs to reflect the state of RNW 0.73.
There are various bugs opened against direct debugging Hermes in RNW, this updates the docs to reflect the coming deprecation of web debugging.
Resolves #928 
N/A
=> Update debugging docs as of RNW 0.73

website/pages/en/support.js
Mark 0.72 as unsupported on the support page.
0.72 has passed its EOL date.
N/A
=> Mark 0.72 as unsupported

docs/run-windows-cli.md
Marks the remote debugging flag as deprecated in the CLI documentation.
Reflect web debugging being deprecated: https://github.com/react-native-community/discussions-and-proposals/discussions/734
Partially resolves https://github.com/microsoft/react-native-windows/issues/12928
Before:
After:
=> Mark remote debugging as deprecated in CLI docs

docs/debugging-javascript.md
Puts Direct Debugging before Web debugging and adds a recommendation to use Web Debugging specifically with Hermes (which can be removed when Hermes is fixed). Also removes developer menu from Web Debugging as it is no longer there.
Updates documentation to better correspond to current state of debugging in 0.74
https://github.com/microsoft/react-native-windows-samples/assets/42554868/74e9726b-d94f-4908-a01f-a30a96f59d77
=> Update Debugging Documentation

docs/setup-ci.md
Updating the CI documentation to work with a 74+ RNW application.
Tried to use our CI documentation to add CI to a 74 application and it did not work straight out the box. Updating our CI documentation to use the right dependencies.  Also added the whole file because it helped me figure out how to get CI working :)
=> Update CI Docs

.spelling, docs/autolink-windows-cli.md, docs/codegen-windows-cli.md, docs/debugging-javascript.md, docs/getting-started.md, docs/hermes.md, docs/init-windows-cli.md, docs/native-code.md, docs/native-modules-autolinking.md, docs/native-modules-setup.md, docs/native-modules-using.md, docs/nuget-update.md, docs/nuget.md, docs/react-native-windows-cli.md, docs/releases.md, docs/run-windows-cli.md, docs/upgrade-app.md, docs/view-managers.md, website/pages/en/init-cli.js, website/sidebars.json, website/siteConfig.js
This PR does multiple things in order to improve the RNW CLI documentation, including:
* Creating separate pages for each CLI command
* Updating existing documentation to point to these new pages where appropriate
* Updated Getting Started to use the new `init-windows` command
* Updated other references to the old `react-native-windows-init` command with links to the new command and changed functionality
* Clarified references where we used "React Native Windows CLI" as a generic term when we mean specific commands within the CLI
To improve out documentation in time for the 0.75 release.
Resolves https://github.com/microsoft/react-native-windows/issues/13394
N/A
=> Overhaul RNW CLI documentation

docs/getting-started.md, website/versioned_docs/version-0.74/getting-started.md
Update our docs since `react-native init` is getting deprecated, and replace with `@react-native-community/cli init`.
To avoid users seeing the deprecation warning, and it not warning when the deprecation happens.
N/A
=> Update getting-started to use @react-native-community/cli for new projects

samples/Calculator/README.md, samples/Calculator/cppwinrt/README.md, samples/Calculator/csharp/README.md, samples/NativeModuleSample/README.md, samples/NativeModuleSample/cppwinrt/README.md, samples/NativeModuleSample/csharp/README.md, samples/README.md
This updates the various steps in our sample readme's with the CLI commands going forward with RN 0.75.
Starting with RN 0.75, the preference is to call `npx @react-native-community/cli` instead of `npx react-native` and also we're deprecating the `npx react-native-windows-init` command in favor of `npx @react-native-community/cli init-windows`.
Resolves https://github.com/microsoft/react-native-windows/issues/13464
N/A
=> Upgrade sample readmes with new CLI commnads

docs/getting-started.md, website/versioned_docs/version-0.75/getting-started.md
Replace `yarn add`  "latest" with a specific semver range.
Newer versions of yarn just add the tag name to the package.json, which is a good way of messing up projects when new versions come out.
N/A
=> Replace npm tag for yarn add

docs/rnw-dependencies.md, website/versioned_docs/version-0.60/rnw-dependencies.md, website/versioned_docs/version-0.61/rnw-dependencies.md, website/versioned_docs/version-0.62/rnw-dependencies.md, website/versioned_docs/version-0.63/rnw-dependencies.md, website/versioned_docs/version-0.64/rnw-dependencies.md, website/versioned_docs/version-0.65/rnw-dependencies.md, website/versioned_docs/version-0.66/rnw-dependencies.md, website/versioned_docs/version-0.71/rnw-dependencies.md
Removed the trailing slash from the download links.
The download link for node doesn't like the trailing slash.
N/A
=> Fix node download link

samples/NativeModuleSample/cpp-lib/example-old/src/App.tsx, samples/NativeModuleSample/cpp-lib/example/src/App.tsx, samples/NativeModuleSample/cpp-lib/package.json, samples/NativeModuleSample/cpp-lib/src/CircleMaskNativeComponent.ts, samples/NativeModuleSample/cpp-lib/src/index.tsx, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/CircleMask.cpp, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/CircleMask.h, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/NativeModuleSample.vcxproj, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/NativeModuleSample.vcxproj.filters, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/ReactPackageProvider.cpp, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/codegen/react/components/NativeModuleSampleSpec/CircleMask.g.h
This PR adds a `CircleMask` native view to the `NativeModuleSample`.
So we have an example of implementing the same native view for both Paper (using Xaml) and Fabric (using Composition).
| New Arch | Old Arch |
|:-:|:-:|
| ![image](https://github.com/user-attachments/assets/0cd5d355-f970-4fbf-9d25-237efed14e1b) | ![image](https://github.com/user-attachments/assets/b707c136-0e5f-4336-9940-01e87bbb7c8f) |
=> Add CircleMask view example to NativeModuleSample

.ado/ci.yml, CodeQL.yml
Adds a simple CI to build the (production) website, so we can start collecting CodeQL scan results.
We need to get CodeQL scanning for the repo.
Resolves #977
N/A
=> Add ADO Production CI

.github/workflows/ci-upgrade.yml, .github/workflows/template-upgradesample.yml
This PR updates the upgrade sample CI to use init-windows instead of react-native-windows-init.
To re-enable the CI.
N/A
=> Fix Upgrade CI

docs/rnm-getting-started.md
This PR fixes a insonsitency in the documentation and updates the init command to the latest date because the current command is resulting in the following error
```
npx react-native@latest init ReactNativeGithub --version 0.76.0
🚨️ The `init` command is deprecated.
- Switch to npx @react-native-community/cli init for the identical behavior.
- Refer to the documentation for information about alternative tools: https://reactnative.dev/docs/getting-started
Exiting...
```
Furthermore, I've removed the path level from the version value so the latest patch will be used (0.76.7)
What is the motivation for this change? Add a few sentences describing the context and overall goals of the pull request's commits.
=> Fix broken init command in documentation

samples/NativeModuleSample/README.md, samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/NativeModuleSample.vcxproj, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/packages.lock.json, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/windows/NativeModuleSample/NativeModuleSample.csproj, samples/NativeModuleSample/csharp/yarn.lock
Upgrades the NativeModule samples to 0.78. 
Part of the 0.78 release.
=> Upgrade NativeModule samples to 0.78

samples/Calculator/cppwinrt/.gitignore, samples/Calculator/cppwinrt/README.md, samples/Calculator/cppwinrt/android/app/build.gradle, samples/Calculator/cppwinrt/android/build.gradle, samples/Calculator/cppwinrt/android/gradle/wrapper/gradle-wrapper.properties, samples/Calculator/cppwinrt/android/gradlew, samples/Calculator/cppwinrt/package-lock.json, samples/Calculator/cppwinrt/package.json, samples/Calculator/cppwinrt/windows/Calculator/Calculator.vcxproj, samples/Calculator/cppwinrt/yarn.lock, samples/Calculator/csharp/.gitignore, samples/Calculator/csharp/README.md, samples/Calculator/csharp/android/app/build.gradle, samples/Calculator/csharp/android/build.gradle, samples/Calculator/csharp/android/gradle/wrapper/gradle-wrapper.properties, samples/Calculator/csharp/android/gradlew, samples/Calculator/csharp/package-lock.json, samples/Calculator/csharp/package.json, samples/Calculator/csharp/windows/calculator/calculator.csproj, samples/Calculator/csharp/yarn.lock
Upgrade cppwinrt and csharp calculator samples to 0.78.
Part of the 0.78 release.
Calculator cppwinrt:
Calculator csharp:
=> Upgrade cppwinrt and csharp Calculator samples

samples/NativeModuleSample/cpp-lib/example-old/package.json, samples/NativeModuleSample/cpp-lib/example-old/windows/NativeModuleSampleExampleOld/packages.lock.json, samples/NativeModuleSample/cpp-lib/example/package.json, samples/NativeModuleSample/cpp-lib/example/windows/NativeModuleSampleExample.Package/packages.lock.json, samples/NativeModuleSample/cpp-lib/example/windows/NativeModuleSampleExample/packages.lock.json, samples/NativeModuleSample/cpp-lib/package.json, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/codegen/react/components/NativeModuleSampleSpec/CircleMask.g.h, samples/NativeModuleSample/cpp-lib/windows/NativeModuleSample/packages.lock.json, samples/NativeModuleSample/cpp-lib/yarn.lock
Upgrade `NativeModuleSample/cpp-lib` to RNW 0.78.4
The example apps crash when using RNW 0.78.2.
N/A
=> Upgrade NativeModuleSample/cpp-lib to RNW 0.78.4

docs/rnm-getting-started.md, website/versioned_docs/version-0.78/rnm-getting-started.md
Update the "Latest release" tag to point to our NPM and Github so that developers are less confused when we don't update the website
One of the most common complaints I get is "The website says the latest release is 0.xx !" when it's actually "0.xx + 3" and I just haven't updated this website. Instead of storing the static string, I'm just gonna have a link to our NPM page and Github releases. Those should both be properly updated. 
Add any relevant screen captures here from before or after your changes.
=> update mac-getting-started page

website/pages/en/support.js
Update support.js for 0.76, re-added older versions to the table, but commented out.
Update 0.76 to be correct, and re-add older versions to the table for posterity, but commented out to prevent the table from growing indefinitely.
Add any relevant screen captures here from before or after your changes.
=> Update support.js for 0.76, re-added older versions

docs/native-modules-advanced.md, docs/native-modules-async.md, docs/native-modules-marshalling-data.md, docs/native-modules.md
Fix links missed by #1034.
Unblock CI/PR checks.
N/A
=> Fix old links

website/pages/en/support.js
Update RNW 0.77 status in support page.
RNW 0.77 is no longer supported.
N/A
=> Update support page for RNW 0.77

.spelling, docs/getting-started.md, docs/init-windows-cli.md, docs/new-architecture.md
This PR updates the documentation to reflect the New Architecture default for new applications in 0.80, and also refreshes the documentation on the differences between the architectures for RNW.
We are switching the default for new projects in 0.80. We are also directing more folks to the "New vs. Old Architecture" page both within the docs and from outside.
Resolves #1046
N/A
=> Update documentation to reflect New Architecture default

docs/getting-started.md, website/versioned_docs/version-0.75/getting-started.md, website/versioned_docs/version-0.76/getting-started.md, website/versioned_docs/version-0.77/getting-started.md, website/versioned_docs/version-0.78/getting-started.md, website/versioned_docs/version-0.79/getting-started.md
Running the first command in React Native Windows' [Getting Started][1] documentation
npx --yes @react-native-community/cli@latest init <projectName> --version "^0.79.0"
fails with
> error Cannot read properties of null (reading 'major').
[Upstream react-native-community/cli docs][2] refer to these versions without quoting them.
Dropping the quotes fixes this issue.
Documentation is incorrect, misleading and discouraging.
Resolves microsoft/react-native-windows#15081.
[1]: https://microsoft.github.io/react-native-windows/docs/getting-started
[2]: https://github.com/react-native-community/cli/blob/main/docs/commands.md
=> Fix version in Getting Started documentation
