microsoft/react-native-windows-samples

README.md
Adding standard text about contributions to the Readme.
=> Contribution policy

docs/index.md
Added a few periods and updated capitalization.
=> Minor typos

.github/workflows/website-ci.yml, .github/workflows/website-publish.yml, .unbroken_exclusions, docs/building-rnw.md, docs/e2e-test-more-about.md, docs/e2e-test.md, docs/flyout-component-windows.md, docs/getting-started.md, docs/iviewwindowsprops-api-windows.md, docs/native-modules-setup.md, docs/native-modules.md, docs/popup-component-windows.md, docs/releases.md, docs/rnw-dependencies.md, docs/view-managers.md, website/.unbroken_exclusions
* Runs unbroken to check links
=> Adding website CI

docs/native-modules.md
Fixing some code samples in native-modules.md.
=> Small fixes in native-modules.md

samples/Calculator/yarn.lock, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/TodosFeed/TodosFeed/yarn.lock
Fix samples vulnerabilities by updating dependency versions
=> update acorn and minimist versions

docs/getting-started.md, docs/rnw-dependencies.md
This addresses [this issue](https://github.com/microsoft/react-native-windows/issues/4436) from the main repo.
=> Update getting-started to 0.61

docs/building-rnw.md, samples/NativeModuleSample/README.md, samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample.sln, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/windows/NativeModuleSample.sln, samples/NativeModuleSample/csharp/windows/NativeModuleSample/FancyMath.cs, samples/NativeModuleSample/csharp/yarn.lock, website/sidebars.json
* Updated docs
* Updated readme links
* Updated both C# and C++/WinRT
Key package.json updates:
```json
"peerDependencies": {
"react": "16.9.0",
"react-native": "^0.61",
"react-native-windows": "^0.61"
},
"devDependencies": {
"react": "16.9.0",
"react-native": "^0.61",
"react-native-windows": "^0.61"
}
```
=> Update Sample Native Modules to RNW 0.61 

website/pages/en/versions.js
* Updating the version page for #48
=> Updating website for 0.61 release

samples/Calculator/README.md, samples/Calculator/package.json, samples/Calculator/yarn.lock
* Updated Calculator with the same dependencies as a new 0.61 app
* Updated readme with commands to launch
Affects issue #35
=> Update Calculator sample to RNW 0.61

.github/workflows/website-ci.yml, docs/e2e-test-more-about.md, docs/native-modules-setup.md, docs/releases.md, docs/rnw-dependencies.md, docs/testing.md, docs/win10-compat.md, website/fix-unbroken.js, website/versioned_docs/version-0.60/e2e-test-more-about.md, website/versioned_docs/version-0.61/e2e-test-more-about.md, websiteguide.md
* Completes the requirements updates for issue #49 
* Fixed fix-unbroken
* Fixed links in websiteguide
* Update CI to still build even if broken links are found
=> Updates for 62 plus others

docs/getting-started.md, docs/native-modules-setup.md, docs/win10-compat.md, website/versioned_docs/version-0.60/win10-compat.md, website/versioned_docs/version-0.61/win10-compat.md
* Update getting started for 62, issue #49
* Updated Windows 10 compat with table
=> More updates for 62

website/core/Footer.js, website/pages/en/index.js
`reactwindows` ➡️ `ReactNativeMSFT`
=> Change Twitter handle

website/pages/en/index.js, website/siteConfig.js, website/static/css/homepage/HeaderHero.css
added macos and windows github buttons near call to action buttons.
fixes #102
=> social links updated

website/pages/en/resources.js
this PR fix text in Resources Page.
=>  fix text in Resources page

samples/TodosFeed/InventorySample/Inventory.App/Controls/WrapPanel/WrapPanel.cs
=> samples: fix typo in comment

website/blog/2020-05-19-rn4mupdadates.md
=> blog date update

website/pages/en/index.js
to enable github buttons under the titles of the individual call to action sections for windows and macos.
=> insignificant changes to push a new pr for social links

website/pages/en/index.js
for some reason they're not getting into master. Trying again with clean branch.
=> Added github social links

website/blog/2019-07-21-updates.md
this PR fix link in Recent Posts when you click appears error 404!.
=> fix link in blogpost

docs/getting-started.md
Closes https://github.com/microsoft/react-native-windows/issues/4505.
=> Add instructions for creating TypeScript template

docs/winui3.md
=> Update for WinUI 3 Preview 1

docs/IRedBoxHandler-api-windows.md, website/blog/2019-07-21-updates.md, website/blog/2019-07-22-roadmap.md, website/versioned_docs/version-0.62/IRedBoxHandler-api-windows.md
With the 0.63 merge we added some more properties to the Redbox error information available to native error handling.
=> Update documentation to include the new properties of the redbox handler

docs/getting-started.md, website/versioned_docs/version-0.62/getting-started.md
Fixes RNW#[4132](https://github.com/microsoft/react-native-windows/issues/4132) and addresses [comment here](https://github.com/microsoft/react-native-windows-samples/pull/161#issuecomment-656776055)
=> Fixes to the getting started commands

docs/windowsbrush-and-theme.md, website/blog/2019-12-3-m3updates.md, website/pages/en/index.js
Minor typos fixed in a few files.
=> Javascript -> JavaScript

.github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-Calculator-pr.yml, .github/workflows/samples-NativeModuleSample-CI.yml, .github/workflows/samples-NativeModuleSample-pr.yml, .github/workflows/samples-ci.yml, .github/workflows/website-pr.yml, README.md, samples/Calculator/README.md, samples/NativeModuleSample/README.md
* Split workflows into CI and PR variants
* Added status badges to readmes
=> Updated workflows and readme status badges

.github/workflows/samples-ci-preview.yml
This attempts to add a new CI that attempts to upgrade each sample to the latest preview version of RNW and see if it still builds
=> Added Samples CI (Preview)

docs/getting-started.md
Fixes #200
Update RN versions and TypeScript template version.
=> Update "Getting Started" With Versions for 0.63

docs/native-modules-async.md, samples/NativeModuleSample/csharp/windows/NativeModuleSample/AsyncMethodExamples.cs
=> Update native-modules-async.md to reflect `Task<T>` support in 0.63

docs/windowsbrush-and-theme.md
Change docs from `windowsbrush` -> `PlatformColor` and `AppTheme` -> `Appearance`
Fixes #167
=> Update docs on PlatformColor and themes

samples/NativeModuleSample/csharp/windows/NativeModuleSample/AsyncMethodExamples.cs
I accidentally updated the samples to match the 0.63 documentation thinking that the samples were versioned jsut like the docs.
This change corrects this and puts the 0.62 sample back for C#.
=> Revert sample update with 0.63 features

website/blog/2020-09-02-63updates.md
Fixed youtube video not embedded correctly and the TOC sidebar not showing headers.
=> Blog bug fixes

website/blog/2020-09-02-63updates.md
The people over on DigitalPrimates asked me to add a link to their blog in our blog, this PR is that addition.
=> Added blog post link for partner

.github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-Calculator-pr.yml, .github/workflows/samples-CameraDemo-ci.yml, .github/workflows/samples-CameraDemo-pr.yml, .github/workflows/samples-NativeModuleSample-CI.yml, .github/workflows/samples-NativeModuleSample-pr.yml, samples/Calculator/yarn.lock, samples/CameraDemo/package.json, samples/CameraDemo/yarn.lock, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/yarn.lock
* Updated yarn.lock in samples with latest versions
* Added --frozen-lockfile to sample ci loops
=> Update samples with 0.63.1

docs/native-modules.md, website/static/css/custom.css
Move some custom styling onto CSS
=> Custom styling CSS

docs/getting-started.md, docs/native-code.md, docs/native-modules.md, website/sidebars.json
Add a doc about RNW apps as UWP apps
Fixes #264
=> UWP native code docs

docs/platform.md, website/sidebars.json
In 0.64 we will expose UniversalApiContract for Platform.Version. Add that to the docs.
=> Add docs for platform detection

website/static/css/react-native.css
=> Adapt to larger monitors

website/versioned_docs/version-0.61/native-modules-setup.md, website/versioned_docs/version-0.62/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md
Parallelizing the changes to the lib template here: https://github.com/microsoft/react-native-windows/pull/6577
=> Update native module setup docs with SolutionDir fix

samples/Calculator/package.json, samples/Calculator/yarn.lock
=> upgrade calculator to 0.63.10

docs/native-modules-async.md, samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample.sln, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/windows/NativeModuleSample.sln, samples/NativeModuleSample/csharp/yarn.lock, website/versioned_docs/version-0.61/native-modules-async.md, website/versioned_docs/version-0.62/native-modules-async.md, website/versioned_docs/version-0.63/native-modules-async.md
Addresses issues in https://github.com/microsoft/react-native-windows/issues/6563 by restoring docs to match the working samples.
=> Fix async native module docs

docs/native-modules.md
=> Document REACT_STRUCT nesting issue

docs/native-code-language-choice.md, docs/native-modules-troubleshooting.md, docs/native-modules.md, website/.unbroken_exclusions, website/fix-unbroken.js, website/sidebars.json, website/versioned_docs/version-0.61/native-modules-marshalling-data.md, website/versioned_docs/version-0.62/native-code-language-choice.md, website/versioned_docs/version-0.62/native-code.md, website/versioned_docs/version-0.62/native-modules-troubleshooting.md, website/versioned_sidebars/version-0.62-sidebars.json, website/versioned_sidebars/version-0.63-sidebars.json
Added a new doc to help explain the choice between C# and C++.
Closes #354
=> Update native language docs

.spelling, docs/native-modules-setup.md
- Version of MSBuild Task that doesn't work
- Bad cache conditions
- Separate yarn build and tsc
- Outdated node version
- Wrong lockfile args
=> Fix some bad GitHub Actions steps

docs/native-modules-async.md, samples/NativeModuleSample/csharp/windows/NativeModuleSample/AsyncMethodExamples.cs, website/versioned_docs/version-0.63/native-modules-async.md
=> Restore sample and docs for CSharp's Task<T>

docs/native-modules-advanced.md
=> Add ReactInitializer section

docs/native-modules-csharp-codegen.md, docs/nuget.md
=> Prep for 0.64 in nuget and C# codegen pages

docs/native-modules-setup.md, docs/supported-community-modules.md, website/versioned_docs/version-0.60/native-modules-setup.md, website/versioned_docs/version-0.61/native-modules-setup.md, website/versioned_docs/version-0.62/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md
Updated website to declare that we are also supporting the orientation-locker module. 
Updated Native Module Setup page to include blurb about updating React Native directory and website documentation when you contribute to or create a native module.
=> Update Community Module Info

docs/getting-started.md
0.64+. No version of TS template yet.
=> Update versions in getting started docs

.spelling, docs/metro-config-out-tree-platforms.md
New terminology used by Metro.
=> Metro blacklist -> exclusionList

docs/view-managers.md
Fixes non-static usage of `DependencyObject.SetValue`
=> Remove SetValue usage

website/versioned_docs/version-0.63/windowsbrush-and-theme.md
adding formatting for windowsbrush text in 0.63
=> Backport doc styling fixes

docs/native-modules-advanced.md, docs/native-modules-setup.md, docs/native-modules.md, docs/view-managers.md, website/versioned_docs/version-0.60/native-modules-advanced.md, website/versioned_docs/version-0.60/native-modules-setup.md, website/versioned_docs/version-0.60/native-modules.md, website/versioned_docs/version-0.60/view-managers.md, website/versioned_docs/version-0.61/native-modules-setup.md, website/versioned_docs/version-0.61/native-modules.md, website/versioned_docs/version-0.61/view-managers.md, website/versioned_docs/version-0.62/native-modules-advanced.md, website/versioned_docs/version-0.62/native-modules-setup.md, website/versioned_docs/version-0.62/native-modules.md, website/versioned_docs/version-0.62/view-managers.md, website/versioned_docs/version-0.63/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules.md, website/versioned_docs/version-0.63/view-managers.md
=> Fix links to sample apps package

docs/view-managers.md
=> add event interfaces, fix some doc bugs

docs/native-modules.md, website/versioned_docs/version-0.60/native-modules.md, website/versioned_docs/version-0.61/native-modules.md, website/versioned_docs/version-0.62/native-modules.md, website/versioned_docs/version-0.63/native-modules.md
fixed inconsistent header formatting & backported through 0.60
=> docs formatting fix for native modules

docs/supported-community-modules.md, website/sidebars.json
Updating the list of modules with Windows implementations and cleaning up the table of contents.
=> v 0.64 modules update and TOC cleanup

docs/view-managers.md
=> Document new IViewManagerCreateWithProperties and IViewManagerRequiresNativeLayout

website/siteConfig.js
=> Switch website to default to 0.64

.github/scripts/GetFolderSize.ps1, .github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-CameraDemo-ci.yml, .github/workflows/samples-NativeModuleSample-CI.yml, .github/workflows/samples-RssReader-CI.yml
Adding this script and calculation in prep for some performance metrics.
=> Add before/after folder size for CI workflows

samples/NativeModuleSample/README.md, samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/yarn.lock
=> Upgrade NativeModuleSample to 0.64

website/README.md
=> fix docusaurus broken link due to url move

docs/getting-started.md, website/versioned_docs/version-0.64/getting-started.md
Issue - https://github.com/microsoft/react-native-windows/issues/7426
=> Adding useHermes tag in the documentation

.spelling, docs/rnw-dependencies.md
=> Overhaul Manual Setup info in rnw-dependencies.md

website/blog/2021-05-25-inking.md
=> Fixed a Markdown typo in the inking blog post

website/blog/2021-06-01-notifications.md
I saw there was a question about notifications on the RNW repo so I figured I'd write a native module for it, and it seemed like a good idea to write a blog post about it.
=> Add Toast notification blog post

docs/getting-started.md
=> Update getting-started to point out Hermes is only supported for C++ projects right now

samples/rssreader/package.json, samples/rssreader/windows/rssreader.sln, samples/rssreader/yarn.lock
=> Fix rssreader sample ARM64 build

.github/workflows/samples-CalculatorNuGet-ci-upgrade.yml, samples/CalculatorNuGet/README.md
=> Added CalculatorNuGet CI (Upgrade)

.github/workflows/samples-Calculator-CI.yml, .github/workflows/samples-CalculatorNuGet-ci-upgrade.yml, .github/workflows/samples-CalculatorNuGet-ci.yml, .github/workflows/samples-CameraDemo-ci-upgrade.yml, .github/workflows/samples-CameraDemo-ci.yml, .github/workflows/samples-NativeModuleSample-CI.yml, .github/workflows/samples-NativeModuleSample-ci-upgrade.yml, .github/workflows/samples-RssReader-CI.yml, .github/workflows/samples-RssReader-ci-upgrade.yml
=> Simplify CI workflows for samples

.github/workflows/samples-NativeModuleSample-ci-upgrade.yml, samples/ContinuousIntegration/GitHubActions/0.62/build-app-ci.yml, samples/ContinuousIntegration/GitHubActions/0.62/build-nativemodule-ci.yml, samples/ContinuousIntegration/GitHubActions/0.63/build-app-ci.yml, samples/ContinuousIntegration/GitHubActions/0.63/build-nativemodule-ci.yml, samples/ContinuousIntegration/GitHubActions/0.64/build-app-ci.yml, samples/ContinuousIntegration/GitHubActions/0.64/build-nativemodule-ci.yml, samples/ContinuousIntegration/GitHubActions/0.65/build-app-ci.yml, samples/ContinuousIntegration/GitHubActions/0.65/build-nativemodule-ci.yml
=> Fix fail-fast in CIs

.spelling, docs/customizing-SDK-versions.md, docs/hermes.md, docs/index-api-windows.md, website/.unbroken_exclusions, website/sidebars.json, website/versioned_docs/version-0.64/customizing-SDK-versions.md, website/versioned_docs/version-0.64/hermes.md, website/versioned_docs/version-0.64/index-api-windows.md, website/versioned_sidebars/version-0.64-sidebars.json
=> Add instructions to customize WinUI/SDK version

samples/Calculator/README.md, samples/CalculatorNuGet/README.md, samples/CameraDemo/README.md, samples/README.md
This PR documents the process I've used to update the samples with each major RNW release.
=> Add upgrade instructions for samples

.spelling, docs/hermes.md
We are removing some limitations which we've worked in RN65.
=> Update hermes documentation for RNW65

docs/win10-compat.md
Target version changed in 0.66, which we will need to update for later
=> Update Windows 10 Compat Table

docs/native-modules-async.md
=> Fix REACT_INIT typo

docs/getting-started.md
=> Update version numbers in getting started for 0.65

docs/customizing-SDK-versions.md, docs/native-code.md, docs/parity-status.md, docs/rnw-dependencies.md, docs/win10-compat.md, docs/windowsbrush-and-theme.md, website/pages/en/index.js, website/versioned_docs/version-0.64/customizing-SDK-versions.md, website/versioned_docs/version-0.64/win10-compat.md
=> Update versioning wording

docs/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md, website/versioned_docs/version-0.64/native-modules-setup.md
=> Fix links to webview repo

.github/dependabot.yml
=> Enable dependabot.yml since dependabot.com is deprecated

.github/security.md
=> Apply Microsoft Security policy

.spelling, docs/hermes.md
Updating docs to reflect the improvements in Hermes
=> Updating docs to reflect the improvements in Hermes

.spelling, docs/native-code.md, website/versioned_docs/version-0.65/native-code.md
Docs for microsoft/react-native-windows#8884
=> Add instructions for using analyze-crash.ps1

.github/pull_request_template.md
**_Why_**
Add initial pull request template to repo.
=> Add Pull Request Template to Repo

docs/customizing-SDK-versions.md
=> Remove `WinUI2xPackageVersion` #588

website/pages/en/resources-showcase.js, website/pages/en/resources.js
1. Removes broken icon in resources page:
Before:
After:
2. Prevents unnatural stretch of xbox img in showcase
Before:
After:
=> Remove broken icon

docs/setup-ci.md
Add certificates information link for more context. 
Resolves #574
=> Add Certificates Information Link

docs/hermes.md
Currently this information is on the main repo, but it would be useful for a public audience.
Resolves #439
=> Add Hermes Inspector Information

docs/supported-community-modules.md
Adds react-native-xaml to the list of supported CMs.
=> Add react-native-xaml to list of supported modules

website/README.md
Add missing step in docs cut steps list. Step necessary so that the broken links aren't check for in the latest versioned doc API files.
=> Update Docs Cut Steps

docs/native-modules-setup.md, docs/setup-ci.md, website/versioned_docs/version-0.61/native-modules-setup.md, website/versioned_docs/version-0.62/native-modules-setup.md, website/versioned_docs/version-0.63/native-modules-setup.md, website/versioned_docs/version-0.64/native-modules-setup.md, website/versioned_docs/version-0.65/native-modules-setup.md, website/versioned_docs/version-0.67/native-modules-setup.md, website/versioned_docs/version-0.67/setup-ci.md
=> Fix broken links to react-native-webview repo

docs/native-modules-setup.md
Fix typo in the `Choose your own adventure` section
Fix hyperlink in the `Documenting Your Module` section
=> Fix typo and link

docs/setup-ci.md, samples/ContinuousIntegration/README.md, website/versioned_docs/version-0.63/native-modules-setup.md, website/versioned_docs/version-0.64/native-modules-setup.md, website/versioned_docs/version-0.65/native-modules-setup.md, website/versioned_docs/version-0.67/setup-ci.md
GitHub Actions have resdesigned their docs and broken our links to them.
=> Fix GH Actions links

website/versioned_docs/version-0.60/getting-started.md, website/versioned_docs/version-0.61/getting-started.md, website/versioned_docs/version-0.62/getting-started.md, website/versioned_docs/version-0.63/getting-started.md
This PR updates some links that sometimes redirect and sometimes don't, with the redirected URL which should just work.
=> Fix Website CI

samples/CalculatorCoreAppNuGet/README.md, samples/CalculatorCoreAppNuGet/package.json, samples/CalculatorCoreAppNuGet/windows/CalculatorCoreAppNuGet/App.cpp, samples/CalculatorCoreAppNuGet/windows/CalculatorCoreAppNuGet/CalculatorCoreAppNuGet.vcxproj, samples/CalculatorCoreAppNuGet/windows/CalculatorCoreAppNuGet/CalculatorCoreAppNuGet.vcxproj.filters, samples/CalculatorCoreAppNuGet/windows/CalculatorCoreAppNuGet/app.config.release.json, samples/CalculatorCoreAppNuGet/windows/CalculatorCoreAppNuGet/packages.config, samples/CalculatorCoreAppNuGet/windows/ExperimentalFeatures.props, samples/CalculatorCoreAppNuGet/yarn.lock
This change aligns the coreapp sample app to the UWP template app, and makes it work correctly in Release mode
Dependent on microsoft/react-native-windows#10351
Show e2e coreapp api for Release mode
=> Make project work in Release, align vcxproj to UWP template

samples/NativeModuleSample/README.md, samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/NativeModuleSample.vcxproj, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/windows/NativeModuleSample/NativeModuleSample.csproj, samples/NativeModuleSample/csharp/yarn.lock
Upgrades NativeModuleSample to .70
Following release of .70 we should update our samples
=> Upgrade NativeModuleSample to .70

docs/win10-vm.md
This PR is going to update the current Windows Local VM version downloadable from Microsoft Developer portal.
Downloadable Windows version for Azure VM is still set to 10.
Windows 10 for Local VM is no more downloadable from that source (check [here](https://developer.microsoft.com/en-gb/windows/downloads/virtual-machines/))
=> Update Windows Local VM version

website/README.md
Add updating Support.js to steps for cutting documentation for a new release.
=> Add Editing Support.js to Cut Steps

docs/rnw-dependencies.md
This PR updates the manual dependency list to align with the current development requirements.
Closes #738
=> Update manual dependency list

website/pages/en/support.js
Added link to new RN support policy within our RNW support documentation.
Resolves #734
=> Added link to new react native support policy to RNW support docs

docs/rnw-dependencies.md, website/versioned_docs/version-0.66/rnw-dependencies.md, website/versioned_docs/version-0.71/rnw-dependencies.md
This PR updates the instructions to include the trailing semi-colon and new line, making it easier to copy/paste into powershell and execute immediately.
=> Update instructions for running rnw-dependencies.ps1 script

docs/popup-component-windows.md
Added description for autoFocus property to documentation of Popup
Resolves [#779]
=> Added autoFocus property to Popup documentation

.github/workflows/samples-Calculator-pr.yml, .github/workflows/samples-CalculatorCoreAppNuGet-pr.yml, .github/workflows/samples-CalculatorNuGet-pr.yml, .github/workflows/samples-NativeModuleSample-pr.yml, .github/workflows/samples-RssReader-pr.yml, .github/workflows/website-pr.yml
This PR adds a "Successful PR Check" job to the end of each PR, so that we can specify that job as required for check-in by the branch protections.
Without this, it's not *required* that PR checks actually pass to check in.
=> Added Successful PR check for branch protections

samples/CalculatorCoreAppNuGet/README.md, samples/CalculatorCoreAppNuGet/package.json, samples/CalculatorCoreAppNuGet/yarn.lock, samples/NativeModuleSample/README.md, samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/NativeModuleSample.vcxproj, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/ReactPackageProvider.cpp, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/windows/NativeModuleSample/NativeModuleSample.csproj, samples/NativeModuleSample/csharp/windows/NativeModuleSample/ReactPackageProvider.cs, samples/NativeModuleSample/csharp/windows/NativeModuleSample/packages.lock.json, samples/NativeModuleSample/csharp/yarn.lock
Upgrade NativeModuleSample and CalculatorCoreApp to .72
Part of release of .72
=> Upgrade NativeModuleSample and CalculatorCoreApp to .72

docs/native-modules.md
Added recent stuff:
- New attributed in package.json
- `REACT_NATIVE_NOREG`
=> Update turbo module document

samples/NativeModuleSample/README.md, samples/NativeModuleSample/cppwinrt/README.md, samples/NativeModuleSample/cppwinrt/package.json, samples/NativeModuleSample/cppwinrt/windows/ExperimentalFeatures.props, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/NativeModuleSample.vcxproj, samples/NativeModuleSample/cppwinrt/windows/NativeModuleSample/ReactPackageProvider.cpp, samples/NativeModuleSample/cppwinrt/yarn.lock, samples/NativeModuleSample/csharp/README.md, samples/NativeModuleSample/csharp/package.json, samples/NativeModuleSample/csharp/windows/ExperimentalFeatures.props, samples/NativeModuleSample/csharp/windows/NativeModuleSample/NativeModuleSample.csproj, samples/NativeModuleSample/csharp/windows/NativeModuleSample/packages.lock.json, samples/NativeModuleSample/csharp/yarn.lock
Upgrade NativeModuleSample to 73 and update upgrade documentation
=> Upgrade NativeModuleSample to 73

website/versioned_docs/version-0.71/rnw-dependencies.md
Updating the current (not next) docs with changes in #908
What is the motivation for this change? Add a few sentences describing the context and overall goals of the pull request's commits.
Resolves [Add Relevant Issue Here]
Add any relevant screen captures here from before or after your changes.
=> Update rnw-dependencies.md with req. to develop in Windows

docs/debugging-javascript.md, website/versioned_docs/version-0.67/debugging-javascript.md, website/versioned_docs/version-0.73/debugging-javascript.md
This PR adds some (hopefully temporary) warnings about issues with Hermes direct debugging.
Our priority is standing up Hermes w/ Direct Debugging as default supported scenario, but we should keep users apprised of key known issues that they may encounter while this work is in progress.
N/A
=> Document current known issues with hermes direct debugging

website/README.md, website/versioned_docs/version-0.73/getting-started.md, website/versioned_docs/version-0.74/getting-started.md
Fixes version for 0.73 and 0,74. Also added a clear note in the instructions for next time! :)
closes https://github.com/microsoft/react-native-windows/issues/13201
=> Fix versions for 73 and 74

website/pages/en/index.js, website/static/css/homepage/HeaderHero.css
Separates linting changes from https://github.com/microsoft/react-native-windows-samples/pull/940 into a separate PR.
=> Fix Formatting on Files for Homepage

samples/README.md
Samples are already gone, remove mention from readme.
Cleanup.
N/A
=> Remove old samples from samples README.md

docs/rnm-getting-started.md
From the GitHub releases it looks like the latest release is 0.76 and not 0.71 ?
=> Update macOS getting started
